#!/usr/bin/env python3
"""Apply the validated WBS/G6 GitHub issue mutations with gh.

This script intentionally reads the dry-run plan generated by
reconcile_wbs_g6.py and writes only the live mutation result artifact. It does
not derive new dispositions.
"""

from __future__ import annotations

import json
import subprocess
import tempfile
import time
from pathlib import Path
from typing import Any


REPO = "Summer-Studentship/Summer-Studentship"
OUT_DIR = Path("docs/workstream/wbs-reconciliation")
PLAN_PATH = OUT_DIR / "wbs_mutation_plan.json"
RESULT_PATH = OUT_DIR / "wbs_mutation_result.json"
GATE_BODY_PATH = OUT_DIR / "g6_theoretical_model_gate.md"
G6_MILESTONE_TITLE = "G6 — Theoretical Hybrid Model Complete"
G6_ISSUE_TITLE = "[G6] Theoretical 2D–3D hybrid model complete"

CLOSE_ISSUES = [56, 57, 58, 59, 63, 65, 66, 67, 68]
COMMENT_ONLY_ISSUES = [60, 61, 62, 64, 69, 70, 8, 9]


def run_gh(args: list[str]) -> dict[str, Any]:
    completed = subprocess.run(
        ["gh", *args],
        check=False,
        text=True,
        capture_output=True,
    )
    return {
        "command": ["gh", *args],
        "returncode": completed.returncode,
        "stdout": completed.stdout.strip(),
        "stderr": completed.stderr.strip(),
        "ok": completed.returncode == 0,
    }


def gh_json(args: list[str]) -> tuple[Any | None, dict[str, Any]]:
    result = run_gh(args)
    if not result["ok"]:
        return None, result
    try:
        return json.loads(result["stdout"] or "null"), result
    except json.JSONDecodeError as exc:
        result["ok"] = False
        result["stderr"] = f"failed to decode JSON: {exc}; raw={result['stdout']}"
        return None, result


def comment_exists(issue_number: int, body: str) -> bool:
    comments, result = gh_json(
        [
            "api",
            f"repos/{REPO}/issues/{issue_number}/comments",
            "--jq",
            ".",
        ]
    )
    if not result["ok"] or not isinstance(comments, list):
        return False
    return any(item.get("body") == body for item in comments if isinstance(item, dict))


def issue_snapshot(issue_number: int) -> dict[str, Any]:
    payload, result = gh_json(
        [
            "issue",
            "view",
            str(issue_number),
            "--repo",
            REPO,
            "--json",
            "number,state,stateReason,title,url",
        ]
    )
    return payload if result["ok"] and isinstance(payload, dict) else {"number": issue_number, "fetch_error": result}


def add_comment(issue_number: int, body: str) -> dict[str, Any]:
    if comment_exists(issue_number, body):
        return {
            "issue_number": issue_number,
            "action": "add_comment",
            "status": "skipped_existing_exact_comment",
        }
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", delete=True) as handle:
        handle.write(body)
        handle.flush()
        result = run_gh(["issue", "comment", str(issue_number), "--repo", REPO, "--body-file", handle.name])
    return {
        "issue_number": issue_number,
        "action": "add_comment",
        "status": "applied" if result["ok"] else "failed",
        "result": result,
    }


def close_issue(issue_number: int) -> dict[str, Any]:
    before = issue_snapshot(issue_number)
    if before.get("state") == "CLOSED":
        return {
            "issue_number": issue_number,
            "action": "close_issue",
            "status": "skipped_already_closed",
            "snapshot": before,
        }
    result = run_gh(["issue", "close", str(issue_number), "--repo", REPO, "--reason", "completed"])
    return {
        "issue_number": issue_number,
        "action": "close_issue",
        "status": "applied" if result["ok"] else "failed",
        "result": result,
        "snapshot": issue_snapshot(issue_number),
    }


def find_or_create_milestone() -> dict[str, Any]:
    milestones, list_result = gh_json(
        [
            "api",
            f"repos/{REPO}/milestones?state=all",
            "--paginate",
            "--jq",
            ".",
        ]
    )
    if isinstance(milestones, list):
        for milestone in milestones:
            if milestone.get("title") == G6_MILESTONE_TITLE:
                return {
                    "status": "existing",
                    "number": milestone.get("number"),
                    "url": milestone.get("html_url"),
                    "api_result": list_result,
                }
    create_payload, create_result = gh_json(
        [
            "api",
            f"repos/{REPO}/milestones",
            "-f",
            f"title={G6_MILESTONE_TITLE}",
            "-f",
            "state=open",
            "-f",
            "description=Theoretical 2D-3D hybrid model complete gate.",
        ]
    )
    if create_result["ok"] and isinstance(create_payload, dict):
        return {
            "status": "created",
            "number": create_payload.get("number"),
            "url": create_payload.get("html_url"),
            "api_result": create_result,
        }
    return {"status": "failed", "api_result": create_result, "list_result": list_result}


def find_or_create_gate_issue(milestone_number: int | None) -> dict[str, Any]:
    issues, list_result = gh_json(
        [
            "issue",
            "list",
            "--repo",
            REPO,
            "--state",
            "all",
            "--limit",
            "200",
            "--json",
            "number,title,url,state",
        ]
    )
    if isinstance(issues, list):
        for issue in issues:
            if issue.get("title") == G6_ISSUE_TITLE:
                return {
                    "status": "existing",
                    "number": issue.get("number"),
                    "url": issue.get("url"),
                    "state": issue.get("state"),
                    "api_result": list_result,
                }
    args = [
        "issue",
        "create",
        "--repo",
        REPO,
        "--title",
        G6_ISSUE_TITLE,
        "--body-file",
        str(GATE_BODY_PATH),
    ]
    if milestone_number is not None:
        args.extend(["--milestone", G6_MILESTONE_TITLE])
    create_result = run_gh(args)
    if create_result["ok"]:
        return {
            "status": "created",
            "url": create_result["stdout"],
            "number": int(create_result["stdout"].rstrip("/").split("/")[-1]),
            "api_result": create_result,
        }
    return {"status": "failed", "api_result": create_result, "list_result": list_result}


def project_status() -> dict[str, Any]:
    payload, result = gh_json(
        [
            "project",
            "list",
            "--owner",
            "Summer-Studentship",
            "--format",
            "json",
        ]
    )
    if result["ok"]:
        return {
            "status": "discovered_project_cli_available",
            "projects": payload,
            "api_result": result,
        }
    return {
        "status": "blocked_missing_project_scope_or_cli_permission",
        "api_result": result,
        "required_scope": "project",
    }


def main() -> int:
    plan = json.loads(PLAN_PATH.read_text(encoding="utf-8"))
    by_issue = {int(row["issue_number"]): row for row in plan}
    applied: list[dict[str, Any]] = []
    failures: list[dict[str, Any]] = []

    milestone = find_or_create_milestone()
    gate_issue = find_or_create_gate_issue(milestone.get("number"))

    for issue_number in CLOSE_ISSUES:
        body = by_issue[issue_number]["comment_body"]
        comment_result = add_comment(issue_number, body)
        applied.append(comment_result)
        if comment_result["status"] == "failed":
            failures.append(comment_result)
            continue
        close_result = close_issue(issue_number)
        applied.append(close_result)
        if close_result["status"] == "failed":
            failures.append(close_result)

    for issue_number in COMMENT_ONLY_ISSUES:
        body = by_issue[issue_number]["comment_body"]
        comment_result = add_comment(issue_number, body)
        applied.append(comment_result)
        if comment_result["status"] == "failed":
            failures.append(comment_result)

    project = project_status()
    status = "applied" if not failures and gate_issue.get("status") != "failed" else "partial_failure"
    result = {
        "generated_at_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "status": status,
        "applied_issue_mutations": applied,
        "failed_issue_mutations": failures,
        "milestone": milestone,
        "gate_issue": gate_issue,
        "project_update": project,
        "unsupported_mutations": [
            {
                "kind": "projects_v2_fields_and_view",
                "target": "WBS GitHub Project",
                "reason": "The GitHub CLI reports that Project commands require the missing OAuth `project` scope. Manual field and saved-view instructions are preserved in github_project_update.md.",
            }
        ],
        "notes": "Generated from validated wbs_mutation_plan.json by apply_wbs_g6_mutations.py.",
    }
    RESULT_PATH.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"mutation status: {status}")
    print(f"milestone: {milestone.get('status')} {milestone.get('url')}")
    print(f"gate issue: {gate_issue.get('status')} {gate_issue.get('url')}")
    if failures:
        print(f"failures: {len(failures)}")
    print(f"project: {project.get('status')}")
    return 1 if failures or gate_issue.get("status") == "failed" else 0


if __name__ == "__main__":
    raise SystemExit(main())
